apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: image-service
    spec:
      containers:
      - name: otto-image-service
        image: ghcr.io/danielmunro/otto-image-service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8082
            name: http
            protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: postgres
                key: host
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgres
                key: port
          - name: S3_REGION
            valueFrom:
              secretKeyRef:
                name: image_service
                key: s3_region
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: image_service
                key: s3_bucket
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      - name: postgres
