/*
 * Otto image service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/danielmunro/otto-image-service/internal"
	"github.com/danielmunro/otto-image-service/internal/kafka"
	"github.com/danielmunro/otto-image-service/internal/middleware"
	_ "github.com/joho/godotenv/autoload"
	"log"
	"net/http"
)

func main() {
	go serveHttp()
	readKafka()
}

func readKafka() {
	log.Print("connecting to kafka")
	kafka.InitializeAndRunLoop()
	log.Print("exit kafka loop")
}

func serveHttp() {
	router := internal.NewRouter()
	log.Print("listening on 8082")
	log.Fatal(http.ListenAndServe(":8082",
		middleware.FileSizeLimit(middleware.ContentTypeMiddleware(router))))
}
