on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      user-service:
        image: ghcr.io/danielmunro/otto-user-service:latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
        ports:
          - 8080:8080
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
      KAFKA_SASL_MECHANISMS: ${{ secrets.KAFKA_SASL_MECHANISMS }}
      KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}
      KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
      KAFKA_SECURITY_PROTOCOL: ${{ secrets.KAFKA_SECURITY_PROTOCOL }}
      POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      SESSION_KEY: ${{ secrets.SESSION_KEY }}
      USER_SERVICE_HOST: ${{ secrets.USER_SERVICE_HOST }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go vet ./...
      - run: go run migrations/*.go
#      - run: go test ./test/...
  build-publish-latest:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $CR_PAT | docker login ghcr.io -u danielmunro --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - run: docker build -t ghcr.io/danielmunro/otto-image-service:latest .
      - run: docker push ghcr.io/danielmunro/otto-image-service:latest
